Repository louiCoder/Node-WebScrapper, pull requests merged in 2019-01, with the labels that each got.

#6 modify readme file
  README.md
Labels: Review me, feedback implemented

#7 Repos credentials
  README.md
Labels: Review me

#12 Modify instructions file
  Instructions.js
Labels: Review me

#14 add packarge.json files
  .gitignore
  package.json
Labels: enhancement
